-- Creating tables --
CREATE TABLE STUDENT(
ID_STUD INT PRIMARY KEY,
NAME_STUD VARCHAR(20),
ORG VARCHAR(20),
CONT VARCHAR(20),
CTY VARCHAR(20),
COUNTRY VARCHAR(20),
DISCNT INT,
SX CHAR
);
CREATE TABLE TEACHER(
ID_TCH INT PRIMARY KEY,
NAMETCH CHAR(18),
CONTTCH VARCHAR(20),
SAL INT,
DOL VARCHAR(20),
SX_TC CHAR,
);
CREATE TABLE COURSE(
ID_CRS INT PRIMARY KEY NOT NULL,
TITLE VARCHAR(20),
DEFCRS VARCHAR(60),
COST INT,
ID_TCH INT FOREIGN KEY REFERENCES TEACHER (ID_TCH) ON DELETE CASCADE, 
HUR INT, 
TYPCRS VARCHAR(20),
);
CREATE TABLE CONTRACTY(
ID_CONT INT PRIMARY KEY NOT NULL,
ID_STUD INT FOREIGN KEY REFERENCES STUDENT (ID_STUD) ON DELETE CASCADE,
DTE DATETIME,
ID_CRS INT FOREIGN KEY REFERENCES COURSE (ID_CRS) ON DELETE CASCADE,
);
